export const CURSOR_LAUNCH_SCRIPT = `// Generated by \`buron setup-ci\`. Files a Buron source via the Cursor SDK.
// Verify the @cursor/sdk API against your installed version: https://cursor.com/docs/sdk
import { Agent } from "@cursor/sdk";

const PROMPT = \`Follow the /launch SKILL installed at .cursor/skills/launch/SKILL.md.

You're running in CI, so use env=ci as the destination prefix.

Gather rich context: full git diff, full commit messages with bodies,
PR description and comments verbatim (via 'gh pr view --json'),
linked issues verbatim, code comments, README/CHANGELOG sections
changed in this branch.

Do NOT compress into a marketing brief. Write a raw source dump per the
SKILL's frontmatter and section structure, then push to Buron via:

  npx buron file write /wiki/sources/ci/<YYYY-MM-DD>-<slug>.md \\\\
    --from-file .buron/sources/ci/<YYYY-MM-DD>-<slug>.md

The Buron-side curator runs asynchronously and synthesises the launch
brief from accumulated sources. Don't poll for assets here.\`;

const agent = await Agent.create({
  apiKey: process.env.CURSOR_API_KEY!,
  model: { id: "composer-2" },
  local: { cwd: process.cwd() },
});

const result = await agent.send(PROMPT);
for await (const event of result.stream()) {
  console.log(event);
}
`;
