export const CURSOR_LAUNCH_SCRIPT = `// Generated by \`buron setup-ci\`. Authors a Buron launch file via the Cursor SDK.
// Verify the @cursor/sdk API against your installed version: https://cursor.com/docs/sdk
import { Agent } from "@cursor/sdk";

const PROMPT = \`A pull request was opened in this repository. Follow the launch
skill installed in this repo (look in .claude/skills/launch/, .cursor/skills/launch/,
.codex/skills/launch/, .github/skills/launch/, or .agents/skills/launch/ for
SKILL.md) and write a launch context file to .buron/launches/<uuid>.md based on
the PR diff.

Do not commit, push, or run any CLI commands. Just write the file.\`;

const agent = await Agent.create({
  apiKey: process.env.CURSOR_API_KEY!,
  model: { id: "composer-2" },
  local: { cwd: process.cwd() },
});

const result = await agent.send(PROMPT);
for await (const event of result.stream()) {
  console.log(event);
}
`;
