export const OPENAI_LAUNCH_SCRIPT = `// Generated by \`buron setup-ci\`. Files a Buron source via the OpenAI Agents SDK.
// Verify the @openai/agents API against your installed version: https://github.com/openai/openai-agents-js
import { Agent, run } from "@openai/agents";

const INSTRUCTIONS = \`Follow the /launch SKILL installed at .codex/skills/launch/SKILL.md.

You're running in CI, so use env=ci as the destination prefix.

Gather rich context: full git diff, full commit messages with bodies,
PR description and comments verbatim (via 'gh pr view --json'),
linked issues verbatim, code comments, README/CHANGELOG sections
changed in this branch.

Do NOT compress into a marketing brief. Write a raw source dump per the
SKILL's frontmatter and section structure, then push to Buron via:

  npx buron file write /wiki/sources/ci/<YYYY-MM-DD>-<slug>.md \\\\
    --from-file .buron/sources/ci/<YYYY-MM-DD>-<slug>.md

The Buron-side curator runs asynchronously and synthesises the launch
brief from accumulated sources. Don't poll for assets here.\`;

const agent = new Agent({
  name: "Buron Launch",
  instructions: INSTRUCTIONS,
});

const result = await run(agent, "File the Buron source for this pull request.");
console.log(result.finalOutput);
`;
