export const OPENAI_LAUNCH_SCRIPT = `// Generated by \`buron setup-ci\`. Authors a Buron launch file via the OpenAI Agents SDK.
// Verify the @openai/agents API against your installed version: https://github.com/openai/openai-agents-js
import { Agent, run } from "@openai/agents";

const INSTRUCTIONS = \`A pull request was opened in this repository. Follow the
launch skill installed in this repo (look in .claude/skills/launch/,
.cursor/skills/launch/, .codex/skills/launch/, .github/skills/launch/, or
.agents/skills/launch/ for SKILL.md) and write a launch context file to
.buron/launches/<uuid>.md based on the PR diff.

Do not commit, push, or run any CLI commands. Just write the file.\`;

const agent = new Agent({
  name: "Buron Launch",
  instructions: INSTRUCTIONS,
});

const result = await run(agent, "Author the launch context file for this pull request.");
console.log(result.finalOutput);
`;
